---
title: "Insights - Base de Dados da Aeronaútica"
author: "Gabriel Marreiros"
date: "`r Sys.Date()`"
output:
  rmdformats::robobook:
    highlight: kate
---

```{r rmarkdown_setup, include=FALSE}
## Global options
knitr::opts_chunk$set(cache = TRUE)
```

```{r import, include=FALSE}
library(data.table)
library(magrittr)

# Importa bases do portal de dados abertos do Governo Federal
# https://dados.gov.br/dataset/ocorrencias-aeronauticas-da-aviacao-civil-brasileira
ocorrencia <- data.table::fread(
  "http://sistema.cenipa.aer.mil.br/cenipa/media/opendata/ocorrencia.csv",
  encoding = "UTF-8"
)

ocorrencia_tipo <- data.table::fread(
  "http://sistema.cenipa.aer.mil.br/cenipa/media/opendata/ocorrencia_tipo.csv",
  encoding = "UTF-8"
)

aeronave <- data.table::fread(
  "http://sistema.cenipa.aer.mil.br/cenipa/media/opendata/aeronave.csv",
  encoding = "UTF-8"
)

fator_contribuinte <- data.table::fread(
  "http://sistema.cenipa.aer.mil.br/cenipa/media/opendata/fator_contribuinte.csv",
  encoding = "UTF-8"
)

recomendacao <- data.table::fread(
  "http://sistema.cenipa.aer.mil.br/cenipa/media/opendata/recomendacao.csv",
  encoding = "UTF-8"
)
```

# XXX



```{r}
reactable::reactable(fator_contribuinte)
```